<?php
require_once 'pdo.php';

$pdo->exec("CREATE TABLE IF NOT EXISTS feeds (ID INTEGER PRIMARY KEY,feed TEXT,maxItems INTEGER)");
$pdo->exec("CREATE TABLE IF NOT EXISTS aggregateFeeds (ID INTEGER PRIMARY KEY,feeds TEXT)");
$pdo->exec("CREATE TABLE IF NOT EXISTS filters (ID INTEGER PRIMARY KEY,feedID INTEGER DEFAULT '-1' REFERENCES feeds(ID) ON UPDATE CASCADE ON DELETE CASCADE,field TEXT,regex TEXT)");
$pdo->exec("CREATE TABLE IF NOT EXISTS errorLog (ID INTEGER PRIMARY KEY,query TEXT,error TEXT,date INTEGER)");







